### ISSUE TITLE
Box2d: Submodule clone fails; build fails if check out latest revision

### ISSUE THREAD

**Issue by Fordi** [gamaral/marshmallow_h#11]
The submodule, I'm sure you know how to fix.

The build fail is a little odder - it seems Box2D started using `nullptr` in some of their tests, which means that the build needs `-std=c++11` added to its CXX flags to properly handle these managed null pointers.

Initially, I added `-std=c++11` to the central CMakeLists.txt CMAKE_CXX_FLAGS - but this breaks marshmalow_h's `bufferio.cpp`.  So I had to settle for putting it into contrib/box2d's `CMakeLists.txt`.

If I have time today, I'll see if I can figure out why bufferio shatters against C++11; it's probably something small, but being able to build against the modern standard is important.

**Comment by Fordi** [comment]
See PR #12

**Comment by Fordi** [comment]
I'm not using it, and marshmallow seems unmaintained.

**Comment by youreperfect** [comment]
Regretfully I must say that Mr. Amaral has passed away.
